### ISSUE TITLE
Further DMA Settings

### ISSUE THREAD

**Issue by eos1d3** [maudeve-it/ST7735S-STM32#2]
Hi,  I am trying to test the library but I am having issue. But I need to confirm the DMA settings:

SPI1_TX (Memory to Peripheral)
Increment Address: Memory (not Peripheral)
Data Width: Byte for Peripheral,  and Byte for Memory

And the SPI speed needs to be <=15MB/s. But it seems settings of 8 or 16 MB/s are allowed. There is no way to set any value between 8 and 16, right?

Thanks!

**Comment by maudeve-it** [comment]
SPI (as all ather devices) is attached to (one of the) uC bus and its speed is defined by the bus speed.
I don't know the uC you refer but, for instance, STM32F411 you see in the video, from the its reference manual you get SPI1 connected to APB2:

![image](https://github.com/maudeve-it/ST7735S-STM32/assets/73774972/a8426b76-2c57-4c31-97dd-2f4be209382f)

Bus speed is related to uC clock and you can set it in CubeMX. In this case APB2 has the same clock as uC clock;

![image](https://github.com/maudeve-it/ST7735S-STM32/assets/73774972/ed963641-43ca-41d7-8b68-64e9c6d7d8f3)

Ypu can act on a prescaler "divisor", dividing clock by 2/4/8.  So, in your case, you can chose between 8 or 16. You cannot select a different speed.

BUT

Normally you can  select uC clock in a wide range of values... That allows you "a wide range of values" of the SPI speed
